<?php
/**
 * @file
 * Hooks and main functionality.
 */


/**
 * Implements hook_menu().
 */
function dcv_database_menu() {
  $items['admin/config/structure/dcv'] = array(
    'title' => t('DCV database'),
    'description' => t('Add data to the backend.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dcv_database_form'),
    'access arguments' => array('administer site'),
    'file' => 'dcv_database.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}
